version: '3.7'

services:
        mongodb:
                container_name: "${SERVICE_NAME}-mongodb"
                image: 'mongo:latest'
                restart: always
                environment:
                        - SERVICE_NAME=${SERVICE_NAME}
                        - DB_USERNAME=${DB_USERNAME}
                        - DB_PWD=${DB_PWD}
                ports:
                        - "27017:27017"
                volumes:
                        - './init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh'
                        - './mongo-volume:/data/db'
