version: '3.7'

services:
        mongodb:
                container_name: '${SERVICE_NAME}-mongodb'
                build:
                        context: .
                        dockerfile: ./deployment/Dockerfile-mongo
                restart: always
                environment:
                        - SERVICE_NAME=${SERVICE_NAME}
                          #                        - MONGO_INITDB_ROOT_USERNAME='db_root_user'
                          #                          - MONGO_INITDB_ROOT_PASSWORD='db_root_pwd'
                        - DB_USERNAME=${DB_USERNAME}
                        - DB_PWD=${DB_PWD}
                ports:
                        - '27017:27017'
                volumes:
                        - './init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh'
                        - './mongo-volume:/data/db'
